name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: autotag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.autotag.outputs.new_tag }}
        release_name: ${{ steps.autotag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Build Package
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Drevision=${{ steps.autotag.outputs.new_tag }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build & Push Docker Image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: burakalmazlar/simple-java-backend
        tags: ${{ steps.autotag.outputs.new_tag }}, latest
        registry: docker.io
        buildArgs: REVISION=${{ steps.autotag.outputs.new_tag }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run docker container on AWS
      uses: ironhalik/docker-over-ssh-action@v1
      with:
        user: ec2-user
        host: ${{ secrets.AWS_HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker system prune --all --force --volumes
          export CNT=$(docker container ls --filter name=simple_java_backend --format '{{.Names}}')
          if [ $CNT == "simple_java_backend" ]; then docker container rm -f simple_java_backend; fi
          docker container run -d -p 8080:8080 --name simple_java_backend burakalmazlar/simple-java-backend:${{ steps.autotag.outputs.new_tag }}

